### ISSUE TITLE
Cannot use this extension with vulkan glsl files

### ISSUE THREAD

**Issue by SoulsD** [cadenasgmbh/vscode-glsllint#1]
To have glslangValidator work properly for vulkan shader, additional arguments needs to be passed.
I propose to add an option to the extension to add arguments : 

```json
"glsllint.glslangValidatorPath": "path/to/glslangValidator",
"glsllint.glslangValidatorAdditionalArguments": [
    "-V"
]
```
Additionnaly, it seems there is currently no way to execute `glslangValidator -V` without generating the binary result of the compilation to spirv shader. Maybe an option to set the output dir (`-o <dir>/<filename>.spv`) could do the trick. (a workaround is to add `-o /tmp/tmp.spv` to the arguments)

**Comment by cnsdato** [comment]
This should be working now with `glsllint.glslangValidatorArgs`

**Comment by DavidMedin** [comment]
I am trying to specify descriptor sets in GLSL using Vulkan. I have `-V` set in `glsllint.glslangValidatorArgs`.
Here is my GLSL code:
```
#version 460

layout(location=0) in vec2 pos;
layout(location=1) in vec3 color;

layout(binding=0,set=0) uniform Transformation{
    mat4 model;
    mat4 proj;
    mat4 view;
}camera;
layout(binding=0,set=1) uniform test{
    int testInt;
    float testFloat;
}tester;

layout(location=0) out vec3 vertColor;

void main(){
    gl_Position = camera.proj * camera.view * camera.model * vec4(pos,0,1);
    vertColor = color; 
}
```
I am getting an error at `layout(binding=0,set=1) uniform` saying `'descriptor set' : only allowed when using GLSL for Vulkan` and `'' : compilation terminated `.

these are the only settings I changed for the GLSL Lint extension in `settings.json`:
```
"glsllint.glslangValidatorPath": "C:\\VulkanSDK\\1.2.141.2\\Bin\\glslangValidator.exe",
 "glsllint.glslangValidatorArgs": "-V",
```
What I have tried:
- I downloaded the newest release from glslang and set `glsllint.glslangValidatorPath` to that path. It didn't change anything.
- using `#define VULKAN 100` instead and with `-V`. Got no different results.
- used `--spirv-val` instead of `-V`, didn't work.
- When I call in my terminal:
 `C:\Users\david\Downloads\glslang-master-windows-x64-Release\bin\glslangValidator.exe -V mainShad.vert`
 It returns `mainShad.vert` and no errors.
- When I remove the everything from `glslangValidatorArgs` and `#define VULKAN 100`, I get the same result.

**Comment by hsimpson** [comment]
@DavidMedin I will have a look into this issue and try to reproduce your problem

**Comment by hsimpson** [comment]
@DavidMedin the ```-V``` (ensure uppercase 'V') parameter needs to write out the SPIR-V byte code. This file will be written into the root of your workspace by default.
If this does not work correctly then you can create a "temp" directory and use the ```-o SPIRV_OUTPUT_FILE``` parameter. Example:
```JSON
"glsllint.glslangValidatorArgs": "-V -o ./temp/out.spv"
```

Please ensure to restart VSCode after you change the settings. Configuration reload is not yet supported see: #21 

I also have tested this with 3 different glslangValdiator.exe version on Windows 10 64bit
- Glslang Version: - 8.13.3559 (current stable release on windows: https://github.com/KhronosGroup/glslang/releases/tag/8.13.3559)
- Glslang Version: 10:11.0.0 (master build: https://github.com/KhronosGroup/glslang/releases/tag/master-tot)
- Glslang Version: 10:11.0.0 (binary from VulkanSDK 1.2.162.1)

If you still have any issues then describe them.

**Comment by DavidMedin** [comment]
That works great. Thanks!

**Comment by MouseChannel** [comment]
i have copied what you did,but did not work;
Im using vulkan 1.3 and glslang 12.0.0

**Comment by hsimpson** [comment]
> i have copied what you did,but did not work; Im using vulkan 1.3 and glslang 12.0.0

Can you describe your problem in more detail?
