### ISSUE TITLE
Support glslify

### ISSUE THREAD

**Issue by riccardoscalco** [cadenasgmbh/vscode-glsllint#4]
Hi, I am using vscode-glsllint with code that requires functions with glslify. For example, I have the following:

```
#pragma glslify: random = require(glsl-random);

float f(vec2 p) {
  return random(p);
}
```

With this, I have the messages `'random' : no matching overloaded function found` and `'' : compilation terminated`, both at line `return random(p);`.

Note that, as a consequence that compilation terminated, all the errors after that line are missed.

Is there any way to use the plugin with glslify?

**Comment by hsimpson** [comment]
The problem is, that glslangValidator only supports compatible files and glslify is like a preprocessor format for glsl, it is not a valid syntax for glsl.

To support glslify, the shaderfile must be preprocessed via glslify and then send to the glslangValidator.
I can imagine to implement this in the future...

**Comment by riccardoscalco** [comment]
Thanks, that would be really useful!

**Comment by hsimpson** [comment]
glslify is now supported
