### ISSUE TITLE
Support for javascript literals

### ISSUE THREAD

**Issue by SnailBones** [cadenasgmbh/vscode-glsllint#6]
I would find this extension very useful if it could support glsl as a javascript literal, like this [syntax highlighting extension](https://marketplace.visualstudio.com/items?itemName=boyswan.glsl-literal). Attempting to do so for me is returning the error: `Wrong parameters when starting glslangValidator. Arguments: --stdin -S unkown`.

**Comment by cnsdato** [comment]
> Attempting to do so for me is returning the error: `Wrong parameters when starting glslangValidator. Arguments: --stdin -S unkown.`
Could you explain this a bit more in detail. To reproduce the problem:
- Example code
- Extension version
- glslangValidator version (you could run this in a shell with `glslangValidator --version`)

**Comment by cnsdato** [comment]
> However, when I save this file, the aforementioned error appears. I suspect the javascript is being interpreted as GLSL.
Yes you are right, the above code will be directly send to the glslangValidator executable and this fails, because it is no valid glsl code.

I let this issue open and labeled to future. Maybe it could be a minor thing to implement...

**Comment by SpaceIm** [comment]
Maybe it's a completely different issue, but since the last update of the extension, I have exactly the same error on windows with all my glsl file.

> Wrong parameters when starting glslangValidator. Arguments: --stdin -S unkown

glslangValidator version:

> Glslang Version: 7.13.3381
ESSL Version: OpenGL ES GLSL 3.20 glslang Khronos. 13.3381
GLSL Version: 4.60 glslang Khronos. 13.3381
SPIR-V Version 0x00010400, Revision 1
GLSL.std.450 Version 100, Revision 1
Khronos Tool ID 8
SPIR-V Generator Version 7
GL_KHR_vulkan_glsl version 100
ARB_GL_gl_spirv version 100

But it's the same with the version of April.

**Comment by Reon90** [comment]
I alwayse see `Wrong parameters when starting glslangValidator. Arguments: --stdin -S unkown` when try to edit .rmiss .rchit .rgen shaders. Could you check or throw correct error message?

**Comment by hsimpson** [comment]
> 
> 
> I always see `Wrong parameters when starting glslangValidator. Arguments: --stdin -S unkown` when try to edit .rmiss .rchit .rgen shaders. Could you check or throw correct error message?

This is already fixed see: https://github.com/cadenasgmbh/vscode-glsllint/issues/7
